{"name": "test_delete_exercise", "status": "broken", "statusDetails": {"message": "TypeError: object Response can't be used in 'await' expression", "trace": "self = <test_async_exercises.TestExercises object at 0x10a8fc230>\nfunction_exercise = ExerciseFixture(request=CreateExerciseRequestSchema(title='Camera forget watch those better player.', course_id='762c7... office company thought accept couple. Congress account fast cover research point pretty.', estimated_time='8 weeks')))\nexercises_client = <clients.exercises.exercises_client.ExercisesClient object at 0x10ac6deb0>\n\n    async def test_delete_exercise(self,\n                                 function_exercise: ExerciseFixture,\n                                 exercises_client: ExercisesClient):\n        # Cоздаем запись, получаем id\n        uuid = function_exercise.response.exercise.id\n        # Делаем запрос на удалениее ранее созданной записи\n>       response = await exercises_client.delete_exercise_api(uuid)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE       TypeError: object Response can't be used in 'await' expression\n\ntest_async_exercises.py:83: TypeError"}, "start": 1751656521981, "stop": 1751656521986, "uuid": "3e3f7d35-d055-45b1-82b6-d77fccfd778b", "historyId": "567f0d2464b0c74251a065c209df22e1", "testCaseId": "567f0d2464b0c74251a065c209df22e1", "fullName": "tests.exprcises.test_async_exercises.TestExercises#test_delete_exercise", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.exprcises"}, {"name": "suite", "value": "test_async_exercises"}, {"name": "subSuite", "value": "TestExercises"}, {"name": "host", "value": "VIS-SSQ05N"}, {"name": "thread", "value": "77794-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.exprcises.test_async_exercises"}]}